-- Insert sample users
INSERT INTO users (username, password) VALUES 
('admin', 'password123'),  -- Change this to a hashed password in production
('user1', 'password123'),   -- Change this to a hashed password in production
('user2', 'password123');   -- Change this to a hashed password in production

-- Insert sample bus schedules
INSERT INTO bus_schedule (departure, type, destination, time) VALUES 
('City Center', 'Express', 'Airport', '08:30:00'),
('Main Station', 'Regular', 'Downtown', '09:00:00'),
('North Terminal', 'Express', 'City Park', '09:30:00'),
('South Station', 'Regular', 'Seaside', '10:00:00');

-- Insert sample bookings (Optional)
INSERT INTO bookings (user_id, bus_id) VALUES 
(1, 1),  -- admin booking on first bus
(2, 2);  -- user1 booking on second bus

INSERT INTO bus_schedule (departure, type, destination, time) VALUES
('Sawantwadi', 'Regular', 'Ajara', '18:15'),
('Sawantwadi', 'Regular', 'Ambegaon', '07:15'),
('Sawantwadi', 'Regular', 'Ambegaon', '08:00'),
('Sawantwadi', 'Regular', 'Ambegaon', '09:15'),
('Sawantwadi', 'Regular', 'Ambegaon', '11:00'),
('Sawantwadi', 'Regular', 'Ambegaon', '12:00'),
('Sawantwadi', 'Regular', 'Ambegaon', '13:00'),
('Sawantwadi', 'Regular', 'Ambegaon', '14:00'),
('Sawantwadi', 'Regular', 'Ambegaon', '15:30'),
('Sawantwadi', 'Regular', 'Ambegaon', '16:45'),
('Sawantwadi', 'Regular', 'Ambegaon', '18:10'),
('Sawantwadi', 'Regular', 'Aronda', '09:30'),
('Sawantwadi', 'Regular', 'Aronda', '10:15'),
('Sawantwadi', 'Regular', 'Aronda', '12:00'),
('Sawantwadi', 'Regular', 'Aronda', '16:30'),
('Sawantwadi', 'Regular', 'Aronda', '18:00'),
('Sawantwadi', 'Regular', 'Asaniye', '12:30'),
('Sawantwadi', 'Regular', 'Babarwadi', '07:00'),
('Sawantwadi', 'Regular', 'Babarwadi', '09:15'),
('Sawantwadi', 'Regular', 'Banda', '11:00'),
('Sawantwadi', 'Regular', 'Bavlat', '09:20'),
('Sawantwadi', 'Regular', 'Bavlat', '06:15'),
('Sawantwadi', 'Regular', 'Bavlat', '18:15'),
('Sawantwadi', 'Regular', 'Bolgaon', '06:45'),
('Sawantwadi', 'Regular', 'Bolgaon', '08:00'),
('Sawantwadi', 'Regular', 'Bolgaon', '09:30'),
('Sawantwadi', 'Regular', 'Bolgaon', '10:45'),
('Sawantwadi', 'Regular', 'Bolgaon', '11:15'),
('Sawantwadi', 'Regular', 'Bolgaon', '13:00'),
('Sawantwadi', 'Regular', 'Bolgaon', '15:30'),
('Sawantwadi', 'Regular', 'Bolgaon', '16:00'),
('Sawantwadi', 'Regular', 'Bolgaon', '16:45'),
('Sawantwadi', 'Regular', 'Bharpal', '08:30'),
('Sawantwadi', 'Regular', 'Bharpal', '12:15'),
('Sawantwadi', 'Regular', 'Borivali', '15:30'),
('Sawantwadi', 'Sleeper', 'Borivali - Sleeper', '19:00'),
('Sawantwadi', 'Regular', 'Devgad', '08:30'),
('Sawantwadi', 'Regular', 'Devgad', '09:15'),
('Sawantwadi', 'Regular', 'Devgad', '11:15'),
('Sawantwadi', 'Regular', 'Devgad', '13:15'),
('Sawantwadi', 'Regular', 'Devgad', '16:30'),
('Sawantwadi', 'Regular', 'DevruKh', '12:30'),
('Sawantwadi', 'Regular', 'Dodamarg', '07:15'),
('Sawantwadi', 'Regular', 'Dodamarg', '08:00'),
('Sawantwadi', 'Regular', 'Dodamarg', '09:30'),
('Sawantwadi', 'Regular', 'Dodamarg', '12:00'),
('Sawantwadi', 'Regular', 'Dodamarg', '15:00'),
('Sawantwadi', 'Regular', 'Dodamarg', '19:30'),
('Sawantwadi', 'Regular', 'Gadhinlaj', '16:00'),
('Sawantwadi', 'Regular', 'Kankavli', '06:30'),
('Sawantwadi', 'Regular', 'Kankavli', '08:00'),
('Sawantwadi', 'Regular', 'Kankavli', '09:30'),
('Sawantwadi', 'Regular', 'Kankavli', '10:45'),
('Sawantwadi', 'Regular', 'Kankavli', '12:00'),
('Sawantwadi', 'Regular', 'Kas', '12:00'),
('Sawantwadi', 'Regular', 'Kolhapur', '06:00'),
('Sawantwadi', 'Regular', 'Kolhapur', '08:00'),
('Sawantwadi', 'Regular', 'Kolhapur', '09:45'),
('Sawantwadi', 'Regular', 'Kolhapur', '12:00'),
('Sawantwadi', 'Regular', 'Kolhapur', '16:00'),
('Sawantwadi', 'Regular', 'Kolhapur', '17:15'),
('Sawantwadi', 'Regular', 'Kudal', '13:20'),
('Sawantwadi', 'Regular', 'Kudal', '15:15'),
('Sawantwadi', 'Regular', 'Kudal', '21:15'),
('Sawantwadi', 'Regular', 'Latur via Kolhapur', '15:15'),
('Sawantwadi', 'Regular', 'Malvan', '06:30'),
('Sawantwadi', 'Regular', 'Malvan', '09:45'),
('Sawantwadi', 'Regular', 'Malvan', '15:00'),
('Sawantwadi', 'Sleeper', 'Mumbai Central - Sleeper', '18:30'),
('Sawantwadi', 'Regular', 'Panjim - Goa', '02:30'),
('Sawantwadi', 'Regular', 'Panjim - Goa', '04:00'),
('Sawantwadi', 'Regular', 'Panjim - Goa', '07:30'),
('Sawantwadi', 'Regular', 'Panjim - Goa', '10:00'),
('Sawantwadi', 'Regular', 'Panjim - Goa', '15:15'),
('Sawantwadi', 'Regular', 'Panjim - Goa', '19:00'),
('Sawantwadi', 'Regular', 'Pune', '07:15'),
('Sawantwadi', 'Regular', 'Pune', '09:30'),
('Sawantwadi', 'Regular', 'Pune', '19:45'),
('Sawantwadi', 'Regular', 'Pune', '22:30'),
('Sawantwadi', 'Regular', 'Ratnagiri', '09:15'),
('Sawantwadi', 'Regular', 'Ratnagiri', '12:30'),
('Sawantwadi', 'Regular', 'Ratnagiri', '15:00'),
('Sawantwadi', 'Regular', 'Sawantwadi - Ganesh Galli', '08:00'),
('Sawantwadi', 'Regular', 'Sawantwadi - Ganesh Galli', '09:30'),
('Sawantwadi', 'Regular', 'Sawantwadi - Ganesh Galli', '11:00'),
('Sawantwadi', 'Regular', 'Sawantwadi - Ganesh Galli', '15:30'),
('Sawantwadi', 'Regular', 'Sawantwadi - Ganesh Galli', '18:15'),
('Sawantwadi', 'Regular', 'Taraknath Mandir', '06:30'),
('Sawantwadi', 'Regular', 'Taraknath Mandir', '11:00'),
('Sawantwadi', 'Regular', 'Taraknath Mandir', '14:00'),
('Sawantwadi', 'Regular', 'Taraknath Mandir', '17:30'),
('Sawantwadi', 'Regular', 'Taraknath Mandir', '19:30'),
('Sawantwadi', 'Regular', 'Vengurla', '06:00'),
('Sawantwadi', 'Regular', 'Vengurla', '07:45'),
('Sawantwadi', 'Regular', 'Vengurla', '11:15'),
('Sawantwadi', 'Regular', 'Vengurla', '14:00'),
('Sawantwadi', 'Regular', 'Vengurla', '18:15'),
('Sawantwadi', 'Regular', 'Vengurla', '19:30'),
('Sawantwadi', 'Regular', 'Vengurla', '22:00');
